package com.example.entity;

import java.util.Date;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.id
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.title
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.first_picture
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private String firstPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.flag
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.views
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private Integer views;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.appreciation
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private Integer appreciation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.share_statement
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private Integer shareStatement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.commentabled
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private Integer commentabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.published
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private Integer published;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.recommend
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private Integer recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.create_time
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.update_time
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.type_id
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.user_id
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.tag_ids
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    private String tagIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.id
     *
     * @return the value of t_blog.id
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.id
     *
     * @param id the value for t_blog.id
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.title
     *
     * @return the value of t_blog.title
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.title
     *
     * @param title the value for t_blog.title
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.first_picture
     *
     * @return the value of t_blog.first_picture
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public String getFirstPicture() {
        return firstPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.first_picture
     *
     * @param firstPicture the value for t_blog.first_picture
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setFirstPicture(String firstPicture) {
        this.firstPicture = firstPicture == null ? null : firstPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.flag
     *
     * @return the value of t_blog.flag
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.flag
     *
     * @param flag the value for t_blog.flag
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.views
     *
     * @return the value of t_blog.views
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.views
     *
     * @param views the value for t_blog.views
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.appreciation
     *
     * @return the value of t_blog.appreciation
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public Integer getAppreciation() {
        return appreciation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.appreciation
     *
     * @param appreciation the value for t_blog.appreciation
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setAppreciation(Integer appreciation) {
        this.appreciation = appreciation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.share_statement
     *
     * @return the value of t_blog.share_statement
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public Integer getShareStatement() {
        return shareStatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.share_statement
     *
     * @param shareStatement the value for t_blog.share_statement
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setShareStatement(Integer shareStatement) {
        this.shareStatement = shareStatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.commentabled
     *
     * @return the value of t_blog.commentabled
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public Integer getCommentabled() {
        return commentabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.commentabled
     *
     * @param commentabled the value for t_blog.commentabled
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setCommentabled(Integer commentabled) {
        this.commentabled = commentabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.published
     *
     * @return the value of t_blog.published
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public Integer getPublished() {
        return published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.published
     *
     * @param published the value for t_blog.published
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setPublished(Integer published) {
        this.published = published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.recommend
     *
     * @return the value of t_blog.recommend
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.recommend
     *
     * @param recommend the value for t_blog.recommend
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.create_time
     *
     * @return the value of t_blog.create_time
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.create_time
     *
     * @param createTime the value for t_blog.create_time
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.update_time
     *
     * @return the value of t_blog.update_time
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.update_time
     *
     * @param updateTime the value for t_blog.update_time
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.type_id
     *
     * @return the value of t_blog.type_id
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.type_id
     *
     * @param typeId the value for t_blog.type_id
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.user_id
     *
     * @return the value of t_blog.user_id
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.user_id
     *
     * @param userId the value for t_blog.user_id
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.tag_ids
     *
     * @return the value of t_blog.tag_ids
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public String getTagIds() {
        return tagIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.tag_ids
     *
     * @param tagIds the value for t_blog.tag_ids
     *
     * @mbggenerated Thu Sep 23 18:06:46 CST 2021
     */
    public void setTagIds(String tagIds) {
        this.tagIds = tagIds == null ? null : tagIds.trim();
    }
}