package com.example.entity;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.id
     *
     * @mbggenerated Thu Sep 23 18:10:39 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.name
     *
     * @mbggenerated Thu Sep 23 18:10:39 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.id
     *
     * @return the value of t_tag.id
     *
     * @mbggenerated Thu Sep 23 18:10:39 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.id
     *
     * @param id the value for t_tag.id
     *
     * @mbggenerated Thu Sep 23 18:10:39 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.name
     *
     * @return the value of t_tag.name
     *
     * @mbggenerated Thu Sep 23 18:10:39 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.name
     *
     * @param name the value for t_tag.name
     *
     * @mbggenerated Thu Sep 23 18:10:39 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}